// Placeholder for Flutter FFI generated code
// This file will be generated by flutter_rust_bridge during Flutter build

pub struct FlutterApi {}

impl FlutterApi {
    pub fn new() -> Self {
        Self {}
    }
}
